### ISSUE TITLE
'mount' command is root only

### ISSUE THREAD

**Issue by ghost** [ShawnMcCool/vagrant-chef#1]
When I run vagrant up I get the following error:

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

``` bash
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` v-csc-1 /tmp/vagrant-chef-1/chef-solo-1/cookbooks
```

If I vagrant ssh into the box and execute the command I get the following message:

``` bash
mount: only root can do that
```

Any ideas on how to fix this?

**Comment by ghost** [comment]
My bad, I had to change the following configuration options:

``` ruby
chef.cookbooks_path = "vagrant-chef/chef/cookbooks"
chef.data_bags_path = "vagrant-chef/chef/data_bags"
```

**Comment by ShawnMcCool** [comment]
You had to change them because you installed the submodule differently?

**Comment by ghost** [comment]
I tend to use a system wide Vagrant installation for all my sites, so I just cloned the repository instead of adding it as a submodule.
