### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by caraya** [ShawnMcCool/vagrant-chef#10]
I've had the following issue when adding vagrant-chef. 

I tried adding the submodule as instructed in the readme. 

[09:12:40]  devbox 2188$ git submodule add git@github.com:ShawnMcCool/vagrant-chef.git
Cloning into vagrant-chef...
The authenticity of host 'github.com (192.30.252.131)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.131' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
Clone of 'git@github.com:ShawnMcCool/vagrant-chef.git' into submodule path 'vagrant-chef' failed

I was able to install it with the command below:

[09:13:11] carlos.araya@caraya-mbp devbox 2189$ git submodule add https://github.com/ShawnMcCool/vagrant-chef.git

Then I got the following error when updating the submodules:

Cloning into chef/cookbooks/apache2...
Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
Clone of 'git@github.com:opscode-cookbooks/apache2.git' into submodule path 'chef/cookbooks/apache2' failed
Failed to recurse into submodule path 'vagrant-chef'

Any idea how to fix this?

**Comment by spencerdeinum** [comment]
You need to have your ssh key setup properly with github.

If the url of the submodule is git@github.com you cannot use http auth.

You should be able to execute `ssh git@github.com` from your command line without error.

**Comment by ShawnMcCool** [comment]
No responses = dead, i guess?
