### ISSUE TITLE
New deps

### ISSUE THREAD

**Issue by seeforschauer** [ShawnMcCool/vagrant-chef#14]
While installing new app I've added following deps  in .gitmodules and cookbooks: 
- chef_handler
- postgresql
- runit
- windows
- xfs
- xml
- yum-epel

What about them? Will you add them to the repo? 
Can I make a pull request?

**Comment by ShawnMcCool** [comment]
I use this repository for only one project, now. So, while I am interested in bringing these in (I can see the additions being useful). Please ensure that they're implemented in a way that doesn't modify the documentation (if possible) and please test them. Thanks!

**Comment by seeforschauer** [comment]
Added sysctl and ohai after tests
