### ISSUE TITLE
Virtual Box Image removed 

### ISSUE THREAD

**Issue by taftse** [ShawnMcCool/vagrant-chef#7]
the virtual box image referenced here https://github.com/ShawnMcCool/vagrant-chef/blob/master/vagrant/vagrantfiles/Vagrantfile#L2 has been removed and returns a 404 when you try to launch the vagrant box

**Comment by ShawnMcCool** [comment]
I'm working on a solution to this.

**Comment by ShawnMcCool** [comment]
I've added a new lamp box and will be making a clean base box as well.
